### ISSUE TITLE
Milestone 5 Feedback

### ISSUE THREAD

**Issue by matthewconnell** [STAT547-UBC-2019-20/group_13#30]
Hi group 13, here's my feedback for this milestone:

Bugs:
- [x] An error occurs if the user clicks ‘X’ on the dropdown box

Layout/Other:
- [x] I don’t think a jitter plot is useful here. Maybe a line plot would look better?
- [x] Try to get the 'country' dropdown box to be beside the box plot.
- [x] For the box plot and violin plot, you don’t need a legend since you only have the one variable there.
- [x] You don’t need to include the usage scenario in your dashboard.

Optional future work:
- [ ] Try having more countries and more generations in the boxplot and violin plot so the user can make comparisons more easily.

Overall, well done!

**Comment by racquellem** [comment]
Hi Matthew,

When I transformed our jitter to line plot: 
````
make_plot3= function(){
  line1 = data %>% 
    ggplot(aes(x=year, y=gdp_per_capita....)) +
    geom_line(aes(fill=country)) +
    xlab("Year") +
    ylab("GDP per capita") +
    scale_y_continuous(labels = scales::dollar_format()) +
    theme_minimal(12) +
    ggtitle("Change of GDP per capita over time") +
    theme(plot.title = element_text(hjust = 0.5))
  
  ggplotly(line1, tooltip=c("text"))
} 
````
I receive the warning message: `warning: Ignoring unknown aesthetics: fill from NULL`, and the graph below is produced:

![newplot](https://user-images.githubusercontent.com/54858652/78309561-4924c480-7519-11ea-83c9-ecb585a1adad.png)

Do you know why it doesn't recognize the fill aesthetic? And how I may fix this?

Thanks,
Racquelle

**Comment by matthewconnell** [comment]
Hi! Yup, I know what it is. In the line:

```geom_line(aes(fill=country)) +```

you should change `fill` to `color`. The `fill` argument in `aes()` is for the color with which you want to *fill* something in. Lines don't get filled in but points do (as well as other `geom`s) so `geom_line` doesn't take a `fill` argument. Hope that helps!

**Comment by racquellem** [comment]
Thanks, that worked. I also have another question:

When I try to add `fill=sex` for my other two plots that are connected to drop-down menus 
e.g.

`````
make_plot1= function(xaxis="Generation X"){
  boxplot = data %>%
    filter(generation==xaxis) %>% 
    ggplot() +
    geom_violin(aes(x=generation, y=suicides_no, fill=sex)) +
    theme_bw(12) +
    xlab("Generation") +
    ylab("Number of Suicides")+
    scale_y_continuous(labels = scales::comma_format())+
    ggtitle("Number of suicides in each generation (1985-2016)") +
    theme(plot.title = element_text(hjust = 0.5))
  
  ggplotly(boxplot, tooltip=c("text"))
}
`````

It turns out like: 

![newplot (1)](https://user-images.githubusercontent.com/54858652/78319167-97938c80-7534-11ea-8e6a-a7f8c4afe90d.png)

Do you know why they're overlapping and how I may be able to fix this as well?

Thank you!
Racquelle

**Comment by matthewconnell** [comment]
Yup, in this line:

```    geom_violin(aes(x=generation, y=suicides_no, fill=sex)) +```

you should change `x=generation` to `x=sex`

**Comment by racquellem** [comment]
Thanks again!
